In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
# Import the data
car_data = pd.read_csv("https://static.bc-edx.com/ai/ail-v-1-0/m12/lesson_1/datasets/car-data-encoded.csv")
car_data

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,0,1,0,2.0,0,2,0,88.6,...,130,5,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,NaN,0,1,0,2.0,0,2,0,88.6,...,130,5,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,NaN,0,1,0,2.0,2,2,0,94.5,...,152,5,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,1,1,0,4.0,3,1,0,99.8,...,109,5,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,1,1,0,4.0,3,0,0,99.4,...,136,5,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,21,1,0,4.0,3,2,0,109.1,...,141,5,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
201,-1,95.0,21,1,1,4.0,3,2,0,109.1,...,141,5,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
202,-1,95.0,21,1,0,4.0,3,2,0,109.1,...,173,5,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
203,-1,95.0,21,0,1,4.0,3,2,0,109.1,...,145,3,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
204,-1,95.0,21,1,1,4.0,3,2,0,109.1,...,141,5,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

In [3]:
# Get the features (everything except the "price" column)
X = car_data.copy().drop(columns="price")
X.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg
0,3,NaN,0,1,0,2.0,0,2,0,88.6,...,4,130,5,3.47,2.68,9.0,111.0,5000.0,21,27
1,3,NaN,0,1,0,2.0,0,2,0,88.6,...,4,130,5,3.47,2.68,9.0,111.0,5000.0,21,27
2,1,NaN,0,1,0,2.0,2,2,0,94.5,...,6,152,5,2.68,3.47,9.0,154.0,5000.0,19,26
3,2,164.0,1,1,0,4.0,3,1,0,99.8,...,4,109,5,3.19,3.40,10.0,102.0,5500.0,24,30
4,2,164.0,1,1,0,4.0,3,0,0,99.4,...,5,136,5,3.19,3.40,8.0,115.0,5500.0,18,22

In [4]:
# Get the target column
y = car_data["price"]
y.head()

0    13495.0
1    16500.0
2    16500.0
3    13950.0
4    17450.0
Name: price, dtype: float64

In [5]:
# Use the Sklearn `train_test_split()` function to split the data into training and testing data
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [6]:
# Display X_train
X_train

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg
90,1,128.0,12,0,0,2.0,3,1,0,94.5,...,4,103,3,2.99,3.47,21.9,55.0,4800.0,45,50
173,-1,65.0,19,1,0,4.0,3,1,0,102.4,...,4,122,5,3.31,3.54,8.7,92.0,4200.0,29,34
93,1,103.0,12,1,0,4.0,4,1,0,94.5,...,4,97,1,3.15,3.29,9.4,69.0,5200.0,31,37
5,2,NaN,1,1,0,2.0,3,1,0,99.8,...,5,136,5,3.19,3.40,8.5,110.0,5500.0,19,25
167,2,134.0,19,1,0,2.0,1,2,0,98.4,...,4,146,5,3.62,3.50,9.3,116.0,4800.0,24,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,1,231.0,12,1,0,2.0,2,2,0,99.2,...,6,181,5,3.43,3.27,9.0,160.0,5200.0,19,25
14,1,NaN,2,1,0,4.0,3,2,0,103.5,...,6,164,5,3.31,3.19,9.0,121.0,4250.0,20,25
92,1,122.0,12,1,0,4.0,3,1,0,94.5,...,4,97,1,3.15,3.29,9.4,69.0,5200.0,31,37
179,3,197.0,19,1,0,2.0,2,2,0,102.9,...,6,171,5,3.27,3.35,9.3,161.0,5200.0,19,24
102,0,108.0,12,1,0,4.0,4,1,0,100.4,...,6,181,5,3.43,3.27,9.0,152.0,5200.0,17,22

In [7]:
# Display X_test
X_test

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg
15,0,NaN,2,1,0,4.0,3,2,0,103.5,...,6,209,5,3.62,3.39,8.00,182.0,5400.0,16,22
9,0,NaN,1,1,1,2.0,2,0,0,99.5,...,5,131,5,3.13,3.40,7.00,160.0,5500.0,16,22
100,0,106.0,12,1,0,4.0,3,1,0,97.2,...,4,120,1,3.33,3.47,8.50,97.0,5200.0,27,34
132,3,150.0,17,1,0,2.0,2,1,0,99.1,...,4,121,5,3.54,3.07,9.31,110.0,5250.0,21,28
68,-1,93.0,9,0,1,4.0,4,2,0,110.0,...,5,183,3,3.58,3.64,21.50,123.0,4350.0,22,25
95,1,128.0,12,1,0,2.0,2,1,0,94.5,...,4,97,1,3.15,3.29,9.40,69.0,5200.0,31,37
159,0,91.0,19,0,0,4.0,2,1,0,95.7,...,4,110,3,3.27,3.35,22.50,56.0,4500.0,38,47
162,0,91.0,19,1,0,4.0,3,1,0,95.7,...,4,98,1,3.19,3.03,9.00,70.0,4800.0,28,34
147,0,89.0,18,1,0,4.0,4,1,0,97.0,...,4,108,5,3.62,2.64,9.00,94.0,5200.0,25,31
182,2,122.0,20,0,0,2.0,3,1,0,97.3,...,4,97,3,3.01,3.40,23.00,52.0,4800.0,37,46
191,0,NaN,20,1,0,4.0,3,1,0,100.4,...,5,136,5,3.19,3.40,8.50,110.0,5500.0,19,24
164,1,168.0,19,1,0,2.0,2,2,0,94.5,...,4,98,1,3.19,3.03,9.00,70.0,4800.0,29,34
65,0,118.0,8,1,0,4.0,3,2,0,104.9,...,4,140,5,3.76,3.16,8.00,120.0,5000.0,19,27
175,-1,65.0,19,1,0,4.0,2,1,0,102.4,...,4,122,5,3.31,3.54,8.70,92.0,4200.0,27,32
73,0,NaN,9,1,0,4.0,3,2,0,120.9,...,8,308,5,3.80,3.35,8.00,184.0,4500.0,14,16
152,1,74.0,19,1,0,4.0,2,1,0,95.7,...,4,92,1,3.05,3.03,9.00,62.0,4800.0,31,38
18,2,121.0,3,1,0,2.0,2,1,0,88.4,...,3,61,1,2.91,3.03,9.50,48.0,5100.0,47,53
82,3,NaN,11,1,1,2.0,2,1,0,95.9,...,4,156,6,3.58,3.86,7.00,145.0,5000.0,19,24
86,1,125.0,11,1,0,4.0,3,1,0,96.3,...,4,122,1,3.35,3.46,8.50,88.0,5000.0,25,32
143,0,102.0,18,1,0,4.0,3,1,0,97.2,...,4,108,5,3.62,2.64,9.00,94.0,5200.0,26,32
60,0,115.0,8,1,0,4.0,3,1,0,98.8,...,4,122,1,3.39,3.39,8.60,84.0,4800.0,26,32
101,0,128.0,12,1,0,4.0,3,1,0,100.4,...,6,181,5,3.43,3.27,9.00,152.0,5200.0,17,22
98,2,168.0,12,1,0,2.0,1,1,0,95.1,...,4,97,1,3.15,3.29,9.40,69.0,5200.0,31,37
30,2,137.0,5,1,0,2.0,2,1,0,86.6,...,4,92,0,2.91,3.41,9.60,58.0,4800.0,49,54
25,1,148.0,4,1,0,4.0,3,1,0,93.7,...,4,90,1,2.97,3.23,9.40,68.0,5500.0,31,38
16,0,NaN,2,1,0,2.0,3,2,0,103.5,...,6,209,5,3.62,3.39,8.00,182.0,5400.0,16,22
168,2,134.0,19,1,0,2.0,1,2,0,98.4,...,4,146,5,3.62,3.50,9.30,116.0,4800.0,24,30
195,-1,74.0,21,1,0,4.0,4,2,0,104.3,...,4,141,5,3.78,3.15,9.50,114.0,5400.0,23,28
97,1,103.0,12,1,0,4.0,4,1,0,94.5,...,4,97,1,3.15,3.29,9.40,69.0,5200.0,31,37
194,-2,103.0,21,1,0,4.0,3,2,0,104.3,...,4,141,5,3.78,3.15,9.50,114.0,5400.0,23,28
67,-1,93.0,9,0,1,4.0,3,2,0,110.0,...,5,183,3,3.58,3.64,21.50,123.0,4350.0,22,25
120,1,154.0,14,1,0,4.0,2,1,0,93.7,...,4,90,1,2.97,3.23,9.40,68.0,5500.0,31,38
154,0,81.0,19,1,0,4.0,4,0,0,95.7,...,4,92,1,3.05,3.03,9.00,62.0,4800.0,27,32
202,-1,95.0,21,1,0,4.0,3,2,0,109.1,...,6,173,5,3.58,2.87,8.80,134.0,5500.0,18,23
79,1,161.0,11,1,1,2.0,2,1,0,93.0,...,4,98,6,3.03,3.39,7.60,102.0,5500.0,24,30
69,0,93.0,9,0,1,2.0,1,2,0,106.7,...,5,183,3,3.58,3.64,21.50,123.0,4350.0,22,25
145,0,102.0,18,1,1,4.0,3,0,0,97.0,...,4,108,5,3.62,2.64,7.70,111.0,4800.0,24,29
55,3,150.0,8,1,0,2.0,2,2,0,95.3,...,2,70,2,NaN,NaN,9.40,101.0,6000.0,17,23
45,0,NaN,6,1,0,4.0,3,1,0,94.5,...,4,90,1,3.03,3.11,9.60,70.0,5400.0,38,43
84,3,NaN,11,1,1,2.0,2,1,0,95.9,...,4,156,6,3.59,3.86,7.00,145.0,5000.0,19,24
146,0,89.0,18,1,0,4.0,4,1,0,97.0,...,4,108,1,3.62,2.64,9.00,82.0,4800.0,28,32
66,0,NaN,8,0,0,4.0,3,2,0,104.9,...,4,134,3,3.43,3.64,22.00,72.0,4200.0,31,39
111,0,161.0,13,1,0,4.0,3,2,0,107.9,...,4,120,5,3.46,2.19,8.40,95.0,5000.0,19,24
153,0,77.0,19,1,0,4.0,4,1,0,95.7,...,4,92,1,3.05,3.03,9.00,62.0,4800.0,31,37
96,1,122.0,12,1,0,4.0,3,1,0,94.5,...,4,97,1,3.15,3.29,9.40,69.0,5200.0,31,37
38,0,106.0,5,1,0,2.0,2,1,0,96.5,...,4,110,0,3.15,3.58,9.00,86.0,5800.0,27,33
24,1,148.0,4,1,0,4.0,2,1,0,93.7,...,4,90,1,2.97,3.23,9.40,68.0,5500.0,31,38
139,2,83.0,18,1,0,2.0,2,1,0,93.7,...,4,108,1,3.62,2.64,8.70,73.0,4400.0,26,31
112,0,161.0,13,0,1,4.0,3,2,0,107.9,...,4,152,3,3.70,3.52,21.00,95.0,4150.0,28,33
29,3,145.0,4,1,1,2.0,2,1,0,95.9,...,4,156,4,3.60,3.90,7.00,145.0,5000.0,19,24
19,1,98.0,3,1,0,2.0,2,1,0,94.5,...,4,90,1,3.03,3.11,9.60,70.0,5400.0,38,43
178,3,197.0,19,1,0,2.0,2,2,0,102.9,...,6,171,5,3.27,3.35,9.30,161.0,5200.0,20,24

In [8]:
# Display y_train
y_train

90      7099.0
173     8948.0
93      7349.0
5      15250.0
167     8449.0
        ...
106    18399.0
14     24565.0
92      6849.0
179    15998.0
102    14399.0
Name: price, Length: 153, dtype: float64

In [9]:
# Display y_test
y_test

15     30760.0
9          NaN
100     9549.0
132    11850.0
68     28248.0
95      7799.0
159     7788.0
162     9258.0
147    10198.0
182     7775.0
191    13295.0
164     8238.0
65     18280.0
175     9988.0
73     40960.0
152     6488.0
18      5151.0
82     12629.0
86      8189.0
143     9960.0
60      8495.0
101    13499.0
98      8249.0
30      6479.0
25      6692.0
16     41315.0
168     9639.0
195    13415.0
97      7999.0
194    12940.0
67     25552.0
120     6229.0
154     7898.0
202    21485.0
79      7689.0
69     28176.0
145    11259.0
55     10945.0
45         NaN
84     14489.0
146     7463.0
66     18344.0
111    15580.0
153     6918.0
96      7499.0
38      9095.0
24      6229.0
139     7053.0
112    16900.0
29     12964.0
19      6295.0
178    16558.0
Name: price, dtype: float64

## Use Feature Selection for X

In [10]:
# Check columns
car_data.columns

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price'],
      dtype='object')

In [11]:
# Features to include: "make", "fuel-type", "num-of-doors", "drive-wheels",
# "length", "width", "height", "engine-size", "fuel-system", "city-mpg"
features = ["make", "fuel-type", "num-of-doors", "drive-wheels", 
            "length", "width", "height", "engine-size", 
            "fuel-system", "city-mpg"]
X = car_data[features]
X.head()

,make,fuel-type,num-of-doors,drive-wheels,length,width,height,engine-size,fuel-system,city-mpg
0,0,1,2.0,2,168.8,64.1,48.8,130,5,21
1,0,1,2.0,2,168.8,64.1,48.8,130,5,21
2,0,1,2.0,2,171.2,65.5,52.4,152,5,19
3,1,1,4.0,1,176.6,66.2,54.3,109,5,24
4,1,1,4.0,0,176.6,66.4,54.3,136,5,18

In [12]:
# Now split the data into training and testing sets again
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [13]:
# Preview X_train
X_train.head()

,make,fuel-type,num-of-doors,drive-wheels,length,width,height,engine-size,fuel-system,city-mpg
90,12,0,2.0,1,165.3,63.8,54.5,103,3,45
173,19,1,4.0,1,175.6,66.5,54.9,122,5,29
93,12,1,4.0,1,170.2,63.8,53.5,97,1,31
5,1,1,2.0,1,177.3,66.3,53.1,136,5,19
167,19,1,2.0,2,176.2,65.6,52.0,146,5,24