In [1]:
import pandas as pd

# Import the data
rent_tx_df = pd.read_csv("https://static.bc-edx.com/ai/ail-v-1-0/m12/lesson_3/datasets/rent_data_tx.csv")
rent_ca_df = pd.read_csv("https://static.bc-edx.com/ai/ail-v-1-0/m12/lesson_3/datasets/rent_data_ca.csv")

In [2]:
# Look at the first few rows of the california data
rent_ca_df.head()

,id,category,title,body,amenities,bathrooms,bedrooms,currency,fee,has_photo,...,price_display,price_type,square_feet,address,cityname,state,latitude,longitude,source,time
0,5668627426,housing/rent/apartment,Studio apartment 2432 Penmar Ave,"This unit is located at 2432 Penmar Ave, Venic...",NaN,NaN,0.0,USD,No,Thumbnail,...,"$1,800",Monthly,132,2432 Penmar Avenue,Venice,CA,33.9932,-118.4609,RentLingo,1577359461
1,5668610290,housing/rent/apartment,Studio apartment 333 Hyde St,"This unit is located at 333 Hyde St, San Franc...",Refrigerator,1.0,0.0,USD,No,Thumbnail,...,"$1,495",Monthly,138,333 Hyde St,San Francisco,CA,37.7599,-122.4379,RentLingo,1577358313
2,5664571820,housing/rent/apartment,Studio apartment 57 Taylor Street,"This unit is located at 57 Taylor Street, San ...",Refrigerator,1.0,0.0,USD,No,Thumbnail,...,"$1,695",Monthly,190,57 Taylor St,San Francisco,CA,37.7599,-122.4379,RentLingo,1577015121
3,5668633573,housing/rent/apartment,Studio apartment 545 Georgia street 717-723 Su...,This unit is located at 545 Georgia street 717...,NaN,1.0,1.0,USD,No,Thumbnail,...,$950,Monthly,200,545 Georgia St 717-723 Sutter St,Vallejo,CA,38.1172,-122.2313,RentLingo,1577359918
4,5668624017,housing/rent/apartment,One BR Arballo Dr 12d,"This unit is located at Arballo Dr 12d, San Fr...",NaN,1.0,1.0,USD,No,Thumbnail,...,"$1,400",Monthly,219,NaN,San Francisco,CA,37.7599,-122.4379,RentLingo,1577359209

In [3]:
# Import the pipeline_utilities module

In [4]:
# Train a model for Texas using the rent_model_generator function

Dropped 47.55% rows
Testing dropped NAs
Mean Squared Error: 82643.70036162561
R-squared: 0.31230880494174273
Adjusted R-squared: 0.24220436272706602
Testing no dropped data
Mean Squared Error: 131471.8123648741
R-squared: 0.3534599410751379
Adjusted R-squared: 0.32058502282472123
Returning no dropped data pipeline

In [5]:
# Train a model for California using the rent_model_generator function

Dropped 76.75% rows
Testing dropped NAs
Mean Squared Error: 6244205.103697039
R-squared: 0.07365087163991613
Adjusted R-squared: -0.4985059429354297
Testing no dropped data
Mean Squared Error: 1012099.0156985378
R-squared: 0.44774760963350513
Adjusted R-squared: 0.3943038299206185
Returning no dropped data pipeline